# Generated by Django 3.1.4 on 2021-01-18 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rk_parser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='url',
            field=models.URLField(default='none', verbose_name='URL'),
            preserve_default=False,
        ),
    ]
