# Generated by Django 3.1.4 on 2021-01-28 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rk_parser', '0003_auto_20210128_2249'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(default='none', max_length=200),
            preserve_default=False,
        ),
    ]
